application: biddingtictactoe
version: 2
runtime: go
api_version: go1.9

threadsafe: yes

handlers:

- url: /((wp|wordpress|blog|member/|data/).*|.+\.php(\..+)?)
  static_files: static/no-robots.txt
  upload: static/no-robots.txt
  expiration: "1d"

- url: /robots.txt$
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "1h"

- url: /.*
  script: _go_app
